name: pokemon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed: ^2.5.1
  go_router: ^13.2.3
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#FFCB05"
  image: assets/app_icon.jpg

  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.jpg"